use rustc_hash::FxHashMap as HashMap;

use super::{registry::Registry, identifier::Identifier};

pub fn generate_block_to_state_map(registry: &Registry) -> HashMap<u16, usize> {
    let blocks = registry.get_block_register();
    let mut map = HashMap::default();
    let list: &[(u8, u8, &str, Vec<(&str, &str)>)] = &[
        (0, 0, "minecraft:air", vec![]),
        (1, 0, "minecraft:stone", vec![]),
        (2, 0, "minecraft:grass", vec![("snowy", "false")]),
        (3, 0, "minecraft:dirt", vec![]),
        (4, 0, "minecraft:cobblestone", vec![]),
        (5, 0, "minecraft:oak_planks", vec![]),
        (6, 0, "minecraft:sapling", vec![("tree", "oak"), ("growth", "0")]),
        (6, 1, "minecraft:sapling", vec![("tree", "spruce"), ("growth", "0")]),
        (6, 2, "minecraft:sapling", vec![("tree", "birch"), ("growth", "0")]),
        (6, 8, "minecraft:sapling", vec![("tree", "oak"), ("growth", "1")]),
        (6, 9, "minecraft:sapling", vec![("tree", "spruce"), ("growth", "1")]),
        (6, 10, "minecraft:sapling", vec![("tree", "birch"), ("growth", "1")]),
        (7, 0, "minecraft:bedrock", vec![]),
        (8, 0, "minecraft:flowing_water", vec![]),
        (8, 1, "minecraft:flowing_water", vec![]),
        (8, 2, "minecraft:flowing_water", vec![]),
        (8, 3, "minecraft:flowing_water", vec![]),
        (8, 4, "minecraft:flowing_water", vec![]),
        (8, 5, "minecraft:flowing_water", vec![]),
        (8, 6, "minecraft:flowing_water", vec![]),
        (8, 7, "minecraft:flowing_water", vec![]),
        (8, 8, "minecraft:flowing_water", vec![]),
        (8, 9, "minecraft:flowing_water", vec![]),
        (8, 10, "minecraft:flowing_water", vec![]),
        (8, 11, "minecraft:flowing_water", vec![]),
        (8, 12, "minecraft:flowing_water", vec![]),
        (8, 13, "minecraft:flowing_water", vec![]),
        (8, 14, "minecraft:flowing_water", vec![]),
        (8, 15, "minecraft:flowing_water", vec![]),
        (9, 0, "minecraft:still_water", vec![]),
        (9, 1, "minecraft:still_water", vec![]),
        (9, 2, "minecraft:still_water", vec![]),
        (9, 3, "minecraft:still_water", vec![]),
        (9, 4, "minecraft:still_water", vec![]),
        (9, 5, "minecraft:still_water", vec![]),
        (9, 6, "minecraft:still_water", vec![]),
        (9, 7, "minecraft:still_water", vec![]),
        (9, 8, "minecraft:still_water", vec![]),
        (9, 9, "minecraft:still_water", vec![]),
        (9, 10, "minecraft:still_water", vec![]),
        (9, 11, "minecraft:still_water", vec![]),
        (9, 12, "minecraft:still_water", vec![]),
        (9, 13, "minecraft:still_water", vec![]),
        (9, 14, "minecraft:still_water", vec![]),
        (9, 15, "minecraft:still_water", vec![]),
        (10, 0, "minecraft:flowing_lava", vec![]),
        (10, 1, "minecraft:flowing_lava", vec![]),
        (10, 2, "minecraft:flowing_lava", vec![]),
        (10, 3, "minecraft:flowing_lava", vec![]),
        (10, 4, "minecraft:flowing_lava", vec![]),
        (10, 5, "minecraft:flowing_lava", vec![]),
        (10, 6, "minecraft:flowing_lava", vec![]),
        (10, 7, "minecraft:flowing_lava", vec![]),
        (10, 8, "minecraft:flowing_lava", vec![]),
        (10, 9, "minecraft:flowing_lava", vec![]),
        (10, 10, "minecraft:flowing_lava", vec![]),
        (10, 11, "minecraft:flowing_lava", vec![]),
        (10, 12, "minecraft:flowing_lava", vec![]),
        (10, 13, "minecraft:flowing_lava", vec![]),
        (10, 14, "minecraft:flowing_lava", vec![]),
        (10, 15, "minecraft:flowing_lava", vec![]),
        (11, 0, "minecraft:still_lava", vec![]),
        (11, 1, "minecraft:still_lava", vec![]),
        (11, 2, "minecraft:still_lava", vec![]),
        (11, 3, "minecraft:still_lava", vec![]),
        (11, 4, "minecraft:still_lava", vec![]),
        (11, 5, "minecraft:still_lava", vec![]),
        (11, 6, "minecraft:still_lava", vec![]),
        (11, 7, "minecraft:still_lava", vec![]),
        (11, 8, "minecraft:still_lava", vec![]),
        (11, 9, "minecraft:still_lava", vec![]),
        (11, 10, "minecraft:still_lava", vec![]),
        (11, 11, "minecraft:still_lava", vec![]),
        (11, 12, "minecraft:still_lava", vec![]),
        (11, 13, "minecraft:still_lava", vec![]),
        (11, 14, "minecraft:still_lava", vec![]),
        (11, 15, "minecraft:still_lava", vec![]),
        (12, 0, "minecraft:sand", vec![]),
        (13, 0, "minecraft:gravel", vec![]),
        (14, 0, "minecraft:ore_gold", vec![]),
        (15, 0, "minecraft:ore_iron", vec![]),
        (16, 0, "minecraft:ore_coal", vec![]),
        (17, 0, "minecraft:log", vec![("tree", "oak")]),
        (17, 1, "minecraft:log", vec![("tree", "spruce")]),
        (17, 2, "minecraft:log", vec![("tree", "birch")]),
        (18, 0, "minecraft:leaves", vec![("tree", "oak"), ("decay", "0")]),
        (18, 1, "minecraft:leaves", vec![("tree", "spruce"), ("decay", "0")]),
        (18, 2, "minecraft:leaves", vec![("tree", "birch"), ("decay", "0")]),
        (18, 8, "minecraft:leaves", vec![("tree", "oak"), ("decay", "1")]),
        (18, 9, "minecraft:leaves", vec![("tree", "spruce"), ("decay", "1")]),
        (18, 10, "minecraft:leaves", vec![("tree", "birch"), ("decay", "1")]),
        (19, 0, "minecraft:sponge", vec![]),
        (20, 0, "minecraft:glass", vec![]),
        (21, 0, "minecraft:ore_lapis", vec![]),
        (22, 0, "minecraft:block_lapis", vec![]),
        (23, 2, "minecraft:dispenser", vec![("facing", "west")]), // TODO: Fix facing
        (23, 3, "minecraft:dispenser", vec![("facing", "east")]),
        (23, 4, "minecraft:dispenser", vec![("facing", "north")]),
        (23, 5, "minecraft:dispenser", vec![("facing", "south")]),
        (24, 0, "minecraft:sandstone", vec![]),
        (25, 0, "minecraft:noteblock", vec![]),
        (26, 0, "minecraft:bed", vec![("facing", "north"), ("part", "foot"), ("occupied","false")]),
        (26, 1, "minecraft:bed", vec![("facing", "west"),  ("part", "foot"), ("occupied", "false")]),
        (26, 2, "minecraft:bed", vec![("facing", "south"), ("part", "foot"), ("occupied", "false")]),
        (26, 3, "minecraft:bed", vec![("facing", "east"),  ("part", "foot"), ("occupied", "false")]),
        (26, 4, "minecraft:bed", vec![("facing", "north"), ("part", "foot"), ("occupied", "true")]),
        (26, 5, "minecraft:bed", vec![("facing", "west"),  ("part", "foot"), ("occupied", "true")]),
        (26, 6, "minecraft:bed", vec![("facing", "south"), ("part", "foot"), ("occupied", "true")]),
        (26, 7, "minecraft:bed", vec![("facing", "east"),  ("part", "foot"), ("occupied", "true")]),
        (26, 8, "minecraft:bed", vec![("facing", "north"), ("part", "head"), ("occupied", "false")]),
        (26, 9, "minecraft:bed", vec![("facing", "west"),  ("part", "head"), ("occupied", "false")]),
        (26, 10, "minecraft:bed", vec![("facing", "south"), ("part", "head"), ("occupied", "false")]),
        (26, 11, "minecraft:bed", vec![("facing", "east"),  ("part", "head"), ("occupied", "false")]),
        (26, 12, "minecraft:bed", vec![("facing", "north"), ("part", "head"), ("occupied", "true")]),
        (26, 13, "minecraft:bed", vec![("facing", "west"),  ("part", "head"), ("occupied", "true")]),
        (26, 14, "minecraft:bed", vec![("facing", "south"), ("part", "head"), ("occupied", "true")]),
        (26, 15, "minecraft:bed", vec![("facing", "east"),  ("part", "head"), ("occupied", "true")]),
        (27, 0, "minecraft:powered_rail", vec![]), // meta
        (28, 0, "minecraft:detector_rail", vec![]), // meta
        (29, 0, "minecraft:sticky_piston", vec![]), // meta
        (30, 0, "minecraft:web", vec![]),
        (31, 0, "minecraft:tall_grass", vec![("type", "dead_bush")]),
        (31, 1, "minecraft:tall_grass", vec![("type", "grass")]),
        (31, 2, "minecraft:tall_grass", vec![("type", "fern")]),
        (32, 0, "minecraft:dead_bush", vec![]),
        (33, 0, "minecraft:piston", vec![]), // meta
        (34, 0, "minecraft:piston_extension", vec![]), // meta
        (35, 0, "minecraft:wool", vec![("color", "white")]),
        (35, 1, "minecraft:wool", vec![("color", "orange")]),
        (35, 2, "minecraft:wool", vec![("color", "magenta")]),
        (35, 3, "minecraft:wool", vec![("color", "light_blue")]),
        (35, 4, "minecraft:wool", vec![("color", "yellow")]),
        (35, 5, "minecraft:wool", vec![("color", "lime")]),
        (35, 6, "minecraft:wool", vec![("color", "pink")]),
        (35, 7, "minecraft:wool", vec![("color", "gray")]),
        (35, 8, "minecraft:wool", vec![("color", "light_gray")]),
        (35, 9, "minecraft:wool", vec![("color", "cyan")]),
        (35, 10, "minecraft:wool", vec![("color", "purple")]),
        (35, 11, "minecraft:wool", vec![("color", "blue")]),
        (35, 12, "minecraft:wool", vec![("color", "brown")]),
        (35, 13, "minecraft:wool", vec![("color", "green")]),
        (35, 14, "minecraft:wool", vec![("color", "red")]),
        (35, 15, "minecraft:wool", vec![("color", "black")]),
        (36, 0, "minecraft:air", vec![]), // moving piston
        (37, 0, "minecraft:yellow_flower", vec![]),
        (38, 0, "minecraft:red_flower", vec![]),
        (39, 0, "minecraft:brown_mushroom", vec![]),
        (40, 0, "minecraft:red_mushroom", vec![]),
        (41, 0, "minecraft:block_gold", vec![]),
        (42, 0, "minecraft:block_iron", vec![]),
        (43, 0, "minecraft:double_slab", vec![("type", "stone")]), // stone
        (43, 1, "minecraft:double_slab", vec![("type", "sandstone")]), // sandstone
        (43, 2, "minecraft:double_slab", vec![("type", "plank")]), // plank
        (43, 3, "minecraft:double_slab", vec![("type", "cobblestone")]), // cobble
        (44, 0, "minecraft:slab", vec![("type", "stone")]), // stone
        (44, 1, "minecraft:slab", vec![("type", "sandstone")]), // sandstone
        (44, 2, "minecraft:slab", vec![("type", "plank")]), // plank
        (44, 3, "minecraft:slab", vec![("type", "cobblestone")]), // cobble
        (45, 0, "minecraft:brick_block", vec![]),
        (46, 0, "minecraft:tnt", vec![]),
        (47, 0, "minecraft:bookshelf", vec![]), // why invis?
        (48, 0, "minecraft:mossy_cobblestone", vec![]),
        (49, 0, "minecraft:obsidian", vec![]),
        (50, 1, "minecraft:torch", vec![("meta", "0")]),
        (50, 2, "minecraft:torch", vec![("meta", "1")]),
        (50, 3, "minecraft:torch", vec![("meta", "2")]),
        (50, 4, "minecraft:torch", vec![("meta", "3")]),
        (50, 5, "minecraft:torch", vec![("meta", "4")]),
        (51, 0, "minecraft:fire", vec![]), // meta
        (52, 0, "minecraft:mob_spawner", vec![]),
        (53, 0, "minecraft:wooden_stairs", vec![("facing", "north")]),
        (53, 1, "minecraft:wooden_stairs", vec![("facing", "south")]),
        (53, 2, "minecraft:wooden_stairs", vec![("facing", "west")]),
        (53, 3, "minecraft:wooden_stairs", vec![("facing", "east")]),
        (54, 0, "minecraft:chest", vec![]),
        (55, 0, "minecraft:redstone_dust", vec![]), // Check power levels as meta
        (56, 0, "minecraft:ore_diamond", vec![]),
        (57, 0, "minecraft:block_diamond", vec![]),
        (58, 0, "minecraft:workbench", vec![]),
        (59, 0, "minecraft:crops", vec![("stage", "0")]),
        (59, 1, "minecraft:crops", vec![("stage", "1")]),
        (59, 2, "minecraft:crops", vec![("stage", "2")]),
        (59, 3, "minecraft:crops", vec![("stage", "3")]),
        (59, 4, "minecraft:crops", vec![("stage", "4")]),
        (59, 5, "minecraft:crops", vec![("stage", "5")]),
        (59, 6, "minecraft:crops", vec![("stage", "6")]),
        (59, 7, "minecraft:crops", vec![("stage", "7")]),
        (60, 0, "minecraft:farmland", vec![("moisture", "0")]),
        (60, 1, "minecraft:farmland", vec![("moisture", "1")]),
        (60, 2, "minecraft:farmland", vec![("moisture", "2")]),
        (60, 3, "minecraft:farmland", vec![("moisture", "3")]),
        (60, 4, "minecraft:farmland", vec![("moisture", "4")]),
        (60, 5, "minecraft:farmland", vec![("moisture", "5")]),
        (60, 6, "minecraft:farmland", vec![("moisture", "6")]),
        (60, 7, "minecraft:farmland", vec![("moisture", "7")]),
        (61, 0, "minecraft:furnace", vec![("facing", "north")]),
        (61, 1, "minecraft:furnace", vec![("facing", "north")]),
        (61, 2, "minecraft:furnace", vec![("facing", "west")]),
        (61, 3, "minecraft:furnace", vec![("facing", "east")]),
        (61, 4, "minecraft:furnace", vec![("facing", "north")]),
        (61, 5, "minecraft:furnace", vec![("facing", "south")]),
        (62, 0, "minecraft:furnace_active", vec![("facing", "north")]),
        (62, 1, "minecraft:furnace_active", vec![("facing", "north")]),
        (62, 2, "minecraft:furnace_active", vec![("facing", "west")]),
        (62, 3, "minecraft:furnace_active", vec![("facing", "east")]),
        (62, 4, "minecraft:furnace_active", vec![("facing", "north")]),
        (62, 5, "minecraft:furnace_active", vec![("facing", "south")]),
        (63, 0, "minecraft:sign", vec![]), // meta
        (64, 0, "minecraft:wooden_door", vec![("facing", "north"), ("half", "bottom"), ("powered", "false")]),
        (64, 1, "minecraft:wooden_door", vec![("facing", "west"), ("half", "bottom"), ("powered", "false")]),
        (64, 2, "minecraft:wooden_door", vec![("facing", "south"), ("half", "bottom"), ("powered", "false")]),
        (64, 3, "minecraft:wooden_door", vec![("facing", "east"), ("half", "bottom"), ("powered", "false")]),
        (64, 4, "minecraft:wooden_door", vec![("facing", "north"), ("half", "bottom"), ("powered", "true")]),
        (64, 5, "minecraft:wooden_door", vec![("facing", "west"), ("half", "bottom"), ("powered", "true")]),
        (64, 6, "minecraft:wooden_door", vec![("facing", "south"), ("half", "bottom"), ("powered", "true")]),
        (64, 7, "minecraft:wooden_door", vec![("facing", "east"), ("half", "bottom"), ("powered", "true")]),
        (64, 8, "minecraft:wooden_door", vec![("facing", "north"), ("half", "top"), ("powered", "false")]),
        (64, 9, "minecraft:wooden_door", vec![("facing", "west"), ("half", "top"), ("powered", "false")]),
        (64, 10, "minecraft:wooden_door", vec![("facing", "south"), ("half", "top"), ("powered", "false")]),
        (64, 11, "minecraft:wooden_door", vec![("facing", "east"), ("half", "top"), ("powered", "false")]),
        (64, 12, "minecraft:wooden_door", vec![("facing", "north"), ("half", "top"), ("powered", "true")]),
        (64, 13, "minecraft:wooden_door", vec![("facing", "west"), ("half", "top"), ("powered", "true")]),
        (64, 14, "minecraft:wooden_door", vec![("facing", "south"), ("half", "top"), ("powered", "true")]),
        (64, 15, "minecraft:wooden_door", vec![("facing", "east"), ("half", "top"), ("powered", "true")]),
        (65, 2, "minecraft:ladder", vec![("facing", "north")]),
        (65, 3, "minecraft:ladder", vec![("facing", "south")]),
        (65, 4, "minecraft:ladder", vec![("facing", "east")]),
        (65, 5, "minecraft:ladder", vec![("facing", "west")]),
        (66, 0, "minecraft:rail", vec![]),
        (67, 0, "minecraft:cobblestone_stairs", vec![("facing", "north")]),
        (67, 1, "minecraft:cobblestone_stairs", vec![("facing", "south")]),
        (67, 2, "minecraft:cobblestone_stairs", vec![("facing", "west")]),
        (67, 3, "minecraft:cobblestone_stairs", vec![("facing", "east")]),
        (68, 0, "minecraft:wall_sign", vec![]), // meta
        (69, 0, "minecraft:lever", vec![]), // meta
        (70, 0, "minecraft:stone_pressure_plate", vec![("powered", "false")]),
        (70, 1, "minecraft:stone_pressure_plate", vec![("powered", "true")]),
        (71, 0, "minecraft:iron_door", vec![("facing", "north"), ("half", "bottom"), ("powered", "false")]),
        (71, 1, "minecraft:iron_door", vec![("facing", "west"), ("half", "bottom"), ("powered", "false")]),
        (71, 2, "minecraft:iron_door", vec![("facing", "south"), ("half", "bottom"), ("powered", "false")]),
        (71, 3, "minecraft:iron_door", vec![("facing", "east"), ("half", "bottom"), ("powered", "false")]),
        (71, 4, "minecraft:iron_door", vec![("facing", "north"), ("half", "bottom"), ("powered", "true")]),
        (71, 5, "minecraft:iron_door", vec![("facing", "west"), ("half", "bottom"), ("powered", "true")]),
        (71, 6, "minecraft:iron_door", vec![("facing", "south"), ("half", "bottom"), ("powered", "true")]),
        (71, 7, "minecraft:iron_door", vec![("facing", "east"), ("half", "bottom"), ("powered", "true")]),
        (71, 8, "minecraft:iron_door", vec![("facing", "north"), ("half", "top"), ("powered", "false")]),
        (71, 9, "minecraft:iron_door", vec![("facing", "west"), ("half", "top"), ("powered", "false")]),
        (71, 10, "minecraft:iron_door", vec![("facing", "south"), ("half", "top"), ("powered", "false")]),
        (71, 11, "minecraft:iron_door", vec![("facing", "east"), ("half", "top"), ("powered", "false")]),
        (71, 12, "minecraft:iron_door", vec![("facing", "north"), ("half", "top"), ("powered", "true")]),
        (71, 13, "minecraft:iron_door", vec![("facing", "west"), ("half", "top"), ("powered", "true")]),
        (71, 14, "minecraft:iron_door", vec![("facing", "south"), ("half", "top"), ("powered", "true")]),
        (71, 15, "minecraft:iron_door", vec![("facing", "east"), ("half", "top"), ("powered", "true")]),
        (72, 0, "minecraft:wooden_pressure_plate", vec![("powered", "false")]),
        (72, 1, "minecraft:wooden_pressure_plate", vec![("powered", "true")]),
        (73, 0, "minecraft:ore_redstone", vec![]),
        (74, 0, "minecraft:ore_redstone_glowing", vec![]),
        (75, 0, "minecraft:redstone_torch_off", vec![]),
        (76, 0, "minecraft:redstone_torch_on", vec![]),
        (77, 0, "minecraft:button", vec![]),
        (78, 0, "minecraft:snow_layer", vec![]),
        (79, 0, "minecraft:ice", vec![]),
        (80, 0, "minecraft:snow", vec![]),
        (81, 0, "minecraft:cactus", vec![]),
        (82, 0, "minecraft:clay_block", vec![]),
        (83, 0, "minecraft:reed", vec![]),
        (84, 0, "minecraft:jukebox", vec![]),
        (85, 0, "minecraft:fence", vec![]),
        (86, 0, "minecraft:pumpkin", vec![("facing", "east")]),
        (86, 1, "minecraft:pumpkin", vec![("facing", "north")]),
        (86, 2, "minecraft:pumpkin", vec![("facing", "west")]),
        (86, 3, "minecraft:pumpkin", vec![("facing", "south")]),
        (87, 0, "minecraft:netherrack", vec![]),
        (88, 0, "minecraft:soulsand", vec![]),
        (89, 0, "minecraft:glowstone_block", vec![]),
        (90, 0, "minecraft:portal", vec![]),
        (91, 0, "minecraft:pumpkin_lantern", vec![("facing", "east")]),
        (91, 1, "minecraft:pumpkin_lantern", vec![("facing", "north")]),
        (91, 2, "minecraft:pumpkin_lantern", vec![("facing", "west")]),
        (91, 3, "minecraft:pumpkin_lantern", vec![("facing", "south")]),
        (92, 0, "minecraft:cake", vec![]),
        (93, 0, "minecraft:repeater_off", vec![]),
        (94, 0, "minecraft:repeater_on", vec![]),
        (95, 0, "minecraft:locked_chest", vec![]),
        (96, 0, "minecraft:trapdoor", vec![]),
    ];
    
    let air = registry.get_blockstate_register().get_index_from_identifier(&"minecraft:sponge".into());
    list.into_iter().for_each(|(id, meta, block, properties)| {
        let identifier = Identifier::from_str(block);
        let blockstate = match blocks.get_element_from_identifier(&identifier) {
            Some(block) => {
                let mut current_blockstate = block.get_default_state();
                
                for (name, value) in properties {
                    current_blockstate = current_blockstate.with(name, value);
                }
                // current_blockstate.get_state_identifier()
                let state_id = registry.get_blockstate_register().get_index_from_identifier(current_blockstate.get_state_identifier());
                state_id
            },
            _ => {log::warn!("Improperly matched id to state: {} -> {}|{}", identifier, id, meta); air},
        };
        map.insert((*id as u16) | ((*meta as u16) << 8), blockstate);
    }); 
    map
}
